treewide: fix prototype compilation errors
this fixes :
error: a function declaration without a
prototype is deprecated in all versions
of C [-Werror,-Wstrict-prototypes]

Signed-off-by: ImSpiDy <SpiDy2713@gmail.com>