drivers: dwc3: fix unused variable warnings
fixes:
../drivers/usb/dwc3/dwc3-msm.c:1001:15: error: unused variable 'dwc' [-Werror,-Wunused-variable]
        struct dwc3     *dwc = dep->dwc;
                         ^
../drivers/usb/dwc3/dwc3-msm.c:1100:19: error: unused variable 'mdwc' [-Werror,-Wunused-variable]
        struct dwc3_msm *mdwc = dev_get_drvdata(dwc->dev->parent);
                         ^
../drivers/usb/dwc3/dwc3-msm.c:1153:15: error: unused variable 'dwc' [-Werror,-Wunused-variable]
        struct dwc3 *dwc = dep->dwc;
                     ^

Signed-off-by: ImSpiDy <SpiDy2713@gmail.com>