android: binder: fix unused variable warnings
fixes
../drivers/android/binder.c:815:13: error: unused function 'binder_worklist_empty' [-Werror,-Wunused-function]
static bool binder_worklist_empty(struct binder_proc *proc,
            ^

Signed-off-by: ImSpiDy <SpiDy2713@gmail.com>